apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-gateway-ingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Assurez-vous de spécifier votre contrôleur d'ingress approprié
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.192.168.58.2.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kong-gateway-proxy
            port:
              number: 80