apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PSTRD/app_configuration.git
    targetRevision: HEAD
    path: charts/web_service
  destination: 
    server: https://kubernetes.default.svc
    namespace: web_service

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
